"""add professionals table and professional_id to appointments

Revision ID: 459aba3ba3d0
Revises: c1e330daa38b
Create Date: 2026-08-21 20:02:44.688095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459aba3ba3d0'
down_revision: Union[str, Sequence[str], None] = 'c1e330daa38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professionals_id'), 'professionals', ['id'], unique=False)
    op.create_index(op.f('ix_professionals_owner_id'), 'professionals', ['owner_id'], unique=False)
    op.add_column('appointments', sa.Column('professional_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_appointments_professional_id'), 'appointments', ['professional_id'], unique=False)
    # NÃO cria a foreign key via ALTER: o dialeto SQLite não suporta
    # ALTER TABLE ADD CONSTRAINT fora do "modo batch" (recria a tabela
    # inteira), e este projeto não habilita PRAGMA foreign_keys de qualquer
    # forma — a integridade é garantida na aplicação (ver _validar_profissional
    # em main.py), igual já acontece com appointments.owner_id.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_professional_id'), table_name='appointments')
    op.drop_column('appointments', 'professional_id')
    op.drop_index(op.f('ix_professionals_owner_id'), table_name='professionals')
    op.drop_index(op.f('ix_professionals_id'), table_name='professionals')
    op.drop_table('professionals')
    # ### end Alembic commands ###
