"""add role column to users

Revision ID: 6036d7e5339c
Revises: c38af38de833
Create Date: 2026-08-21 18:34:48.836838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6036d7e5339c'
down_revision: Union[str, Sequence[str], None] = 'c38af38de833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), server_default='user', nullable=False))
    # ### end Alembic commands ###

    # Backfill manual: antes desta migration, o "super admin" era decidido
    # comparando o username com a string "yuri" na unha (ver main.py). Quem
    # já tinha essa conta continua com o mesmo poder, agora via role="admin".
    op.execute("UPDATE users SET role = 'admin' WHERE lower(username) = 'yuri'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
