"""add client_phone and telegram reminder fields to appointments

Revision ID: c1e330daa38b
Revises: f3c491defaa6
Create Date: 2026-08-21 19:48:55.110773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e330daa38b'
down_revision: Union[str, Sequence[str], None] = 'f3c491defaa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('client_phone', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('telegram_link_token', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('reminder_sent', sa.Boolean(), server_default='0', nullable=False))
    op.create_index(op.f('ix_appointments_telegram_link_token'), 'appointments', ['telegram_link_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_telegram_link_token'), table_name='appointments')
    op.drop_column('appointments', 'reminder_sent')
    op.drop_column('appointments', 'telegram_chat_id')
    op.drop_column('appointments', 'telegram_link_token')
    op.drop_column('appointments', 'client_phone')
    # ### end Alembic commands ###
