"""add client_email to appointments

Revision ID: f3c491defaa6
Revises: 6036d7e5339c
Create Date: 2026-08-21 18:41:36.610075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c491defaa6'
down_revision: Union[str, Sequence[str], None] = '6036d7e5339c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('client_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'client_email')
    # ### end Alembic commands ###
